# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: APP_NAME_dev

test:
  <<: *common
  database: APP_NAME_test

production:
  <<: *common
  database: APP_NAME
